# -*- coding: utf-8 -*-
# Design-Analyse Datensatz — erhoben am 16.08.2026 via Chrome (Computed Styles + Screenshots)

SITES = [
{
 "slug":"domaene-wachau","name":"Domäne Wachau","url":"https://www.domaene-wachau.at/de/",
 "cat":"Marke + Shop","catKey":"marke","score":3,"platform":"WordPress (Enfold) + WooCommerce",
 "claim":"Institution. Breit, laut, technisch solide – aber kein Premium-Gefühl.",
 "verdict":"Die größte und inhaltsreichste Seite der Liste. Der schwarze Intro-Screen mit dem gesetzten Logo verspricht Hochwertigkeit, danach kippt der Auftritt in einen sehr klassischen WordPress-Aufbau mit Instagram-Feed, Newsletter-Popup und Rabattlogik. Die Typografie besteht ausschließlich aus einer einzigen Grotesk (Interstate) – kein einziger Serif-Akzent außer im Logo. Für eine Genossenschaft mit dieser Größe stimmig, für ein Familienweingut im Premiumsegment deutlich zu breit und zu funktional.",
 "palette":[("#0a0a0a","Headline-Schwarz"),("#282b2e","Dunkelgrau Sektion"),("#81827b","Markengrau (warm)"),("#82847f","Fließtext-Grau"),("#444444","Body"),("#f8f8f8","Sektionsfläche"),("#eeeeee","Trennfläche"),("#ffffff","Grund")],
 "fonts":"Interstate (einzige Textschrift, alle Schnitte)",
 "type":[("H1","Interstate 66/88 px · w700 · UPPERCASE","Das Weingut"),("H2","Interstate 22/28 px · w700","Zwischenüberschrift"),("H3","Interstate 20/20 px · w700 · UPPERCASE","Label"),("Body","Interstate 18/25 px · w400 · #444","Fließtext im Content"),("Nav","Interstate 18 px · w700 · UPPERCASE","MENÜ / SHOP"),("Footer","Interstate 11/10 px · w400","Kleingedrucktes")],
 "layout":"Container bis 2180 px, Sektions-Padding 70–120 px, Seitenlänge 5.522 px. Vollbild-Intro mit Ladeanimation, danach klassische Sektionsfolge. Logo sitzt fix und überlagert beim Scrollen den Content.",
 "imagery":"27 Bilder, überwiegend 1:1 (13×) und 16:9 (9×), 1 Video. Dunkle Kellerfotografie, Porträt-Mosaik aller Weinhauer:innen, Drohnen-/Landschaftsmotive. Bildstimmung uneinheitlich.",
 "commerce":"WooCommerce mit Side-Cart. Shop-Button dauerhaft im Header, Flaschen-Karussell mit Jahrgang + Ried, CTA „WEINE FINDEN“. Rabattlogik über Newsletter (-10 %).",
 "motion":"Intro-Loader, Scroll-Reveals, horizontales Flaschen-Karussell.",
 "take":["Ried-/Lagen-Systematik als eigener Navigationszweig („Weingärten & Rieden“)","Sehr dunkler, ruhiger Einstiegsscreen mit reduziertem Claim","Konsequente Verwendung genau einer Schriftfamilie über die gesamte Seite"],
 "avoid":["Newsletter-Popup mit Rabatt schon vor dem ersten Scroll","Instagram-Feed-Kachelwand kurz vor dem Footer","Ladeanimation, die den Content mehrere Sekunden blockiert","Fixes Logo, das über den Text scrollt"],
 "shots":[("domaene-wachau-1.jpg","Intro-Screen: schwarz, gesetzte Serif-Wortmarke, Claim in Versalien"),("domaene-wachau-2.jpg","Flaschen-Karussell mit Jahrgang/Ried und dunkler Kellersektion"),("domaene-wachau-3.jpg","Instagram-Kachelwand und Footer mit Newsletterformular")],
},
{
 "slug":"polz","name":"Weingut Polz","url":"https://weingutpolz.at/",
 "cat":"Marke + Shop","catKey":"marke","score":4,"platform":"Shopify",
 "claim":"Der beste E-Commerce-Auftritt der österreichischen Liste.",
 "verdict":"Sauber gebaute Shopify-Seite mit echtem Gestaltungswillen: Sandton als Grundfläche, Tiefseeblau für Typo, Olivgrün als dritte Farbe. Libre Bodoni gibt den Headlines Charakter, Montserrat hält die Oberfläche neutral. Herausragend ist die illustrierte Lagenpyramide – ein eigenes, gezeichnetes Erklärstück statt Stockmaterial. Abgezogen wird für die Stapelung aus Altersabfrage, Cookie-Banner und Treueprogramm-Badge sowie die sehr präsente Rabattkommunikation.",
 "palette":[("#c7c2b7","Sand (Grundfläche)"),("#0a2237","Tiefseeblau (Typo)"),("#4f5a32","Olivgrün (Sektion)"),("#ffffff","Weiß"),("#171717","Fast-Schwarz")],
 "fonts":"Libre Bodoni (Display) + Montserrat (UI/Body)",
 "type":[("H1","Libre Bodoni 51/51 px · w400 · UPPERCASE · weiß","WEINGUT POLZ – FAMILIENWEINGUT SEIT 1912"),("H2","Libre Bodoni 22/22 px · w400 · UPPERCASE · #0a2237","Sektionstitel"),("Body","Montserrat 15/19 px · w400","Fließtext"),("Nav","Montserrat 15 px · UPPERCASE","WEINGUT / HERKUNFT / REBSORTEN")],
 "layout":"Container 1280 px, Sektions-Padding 72 / 36 px, Seitenlänge 8.828 px. Sticky Announcement-Bar über dem Header, Header in Sandfläche, danach Vollbild-Landschaftsbild mit Headline unten links.",
 "imagery":"18 Bilder, fast ausschließlich 1:1. Vollbild-Weingartenpanorama als Hero. Highlight: handgezeichnete/aquarellierte Lagenpyramide (Gebietswein → Ortswein → Riedenwein → GSTK).",
 "commerce":"Warenkorb + Konto im Header, Pill-Buttons mit 60 px Radius, Filter-Chips für Weinkategorien, Treueprogramm-Badge „JETZT VORTEILE SICHERN“ fix unten rechts, Announcement „5 % Rabatt ab Erstbestellung“.",
 "motion":"Karussell mit Pfeil-Steuerung, sanfte Hover-States, sonst ruhig.",
 "take":["Sandfarbene Grundfläche statt Weiß – wirkt sofort wertiger","Eigene Illustration für die Lagenpyramide statt Foto oder Tabelle","Display-Serif nur für Headlines, Grotesk für alles Funktionale","Filter-Chips als ruhige Pills statt Dropdown-Wüste"],
 "avoid":["Drei Overlays hintereinander (Alter, Cookies, Treueprogramm)","Rabatt als erste Botschaft in der Announcement-Bar","Dauerhaft sichtbares Loyalty-Badge über dem Content"],
 "shots":[("polz-1.jpg","Hero: Sand-Header, Vollbild-Weingarten, Bodoni-Headline unten links"),("polz-2.jpg","Illustrierte Lagenpyramide mit Filter-Chips darunter")],
},
{
 "slug":"sattlerhof","name":"Sattlerhof","url":"https://sattlerhof.at/",
 "cat":"Marke / Gastgeber","catKey":"marke","score":4,"platform":"WordPress + Bootstrap, Borlabs Cookie",
 "claim":"Gastgeber-Auftritt: Weingut, Restaurant und Hotel unter einer Marke.",
 "verdict":"Der ruhigste österreichische Auftritt der Liste. Cremeweiße Grundfläche, ein einziger warmer Ziegelrot-Akzent, mittig gesetzte Wortmarke, Hamburger links, Buchen- und Shop-Icon als handgezeichnete Stempel rechts. Die Seite ist als animierter One-Pager gebaut und erzählt Weingut, Kulinarik und Hotel gleichwertig – genau das Modell, das für ein Weingut mit Verkostung und Gastronomie funktioniert. Größte Schwäche: eine harte Consent-Wall blockiert den Zugang komplett, und der Fließtext ist mit 12 px zu klein.",
 "palette":[("#f5f1e2","Creme (Grundfläche)"),("#fff1df","Warmes Creme"),("#c03a2c","Ziegelrot (Akzent)"),("#212529","Fast-Schwarz"),("#4a4a4a","Body-Grau"),("#626262","Sekundärtext")],
 "fonts":"Utopia (Serif, Labels) + DIN (Headlines) + Inter (Body)",
 "type":[("H2","DIN 26/35 px · w600 · UPPERCASE · #212529","WEINGUT / KULINARIK / HOTEL"),("H3","Utopia 28/33 px · w500 · ls 1.5 px · UPPERCASE · #c03a2c","Roter Serif-Kicker"),("Body","Inter 12/22 px · w400 · ls 0.4 px · #4a4a4a","Fließtext (deutlich zu klein)")],
 "layout":"Bootstrap-Container 1140 px, Seitenlänge 3.825 px. Mittig gesetzte Wortmarke, Navigation hinter Hamburger, Sprache und Buchungs-Icons rechts. Scroll-animierter One-Pager.",
 "imagery":"Wenige, dafür sehr große Motive: Vollbild-Landschaft über dem Hof, Videosequenzen, Food-Stillleben. Einheitlich warme, leicht entsättigte Farbstimmung.",
 "commerce":"Kein Shop im Vordergrund. Stattdessen zwei gleichrangige Icon-Buttons: „AUFENTHALT BUCHEN“ und „SHOP“ – beide als handgezeichnete Stempel. Auszeichnungsleiste im Footer (Michelin, Gault&Millau, Falstaff, Respekt).",
 "motion":"Starke Scroll-Choreografie mit Ein- und Ausblendungen, teilweise Scroll-Jacking.",
 "take":["Drei Geschäftsbereiche gleichwertig im Footer und in der Navigation","Genau ein warmer Akzentton auf cremeweißem Grund","Handgezeichnete Icons statt Standard-Piktogramme","Auszeichnungsleiste als ruhige Monochrom-Reihe, nicht als bunte Badges"],
 "avoid":["Consent-Wall, die den Zugang zur Seite komplett blockiert","12 px Fließtext","Scroll-Animation, die das Zurückscrollen unberechenbar macht"],
 "shots":[("sattlerhof-1.jpg","Header: mittige Wortmarke, Hamburger links, Buchen/Shop-Stempel rechts"),("sattlerhof-2.jpg","Footer mit drei gleichrangigen Bereichen Weingut / Kulinarik / Hotel")],
},
{
 "slug":"mazzei","name":"Mazzei (Toskana)","url":"https://eu.mazzei.it/",
 "cat":"Marke premium","catKey":"marke","score":5,"platform":"Shopify",
 "claim":"Der internationale Premium-Maßstab in dieser Liste.",
 "verdict":"Das ist der Auftritt, an dem sich ein Premium-Weingut messen sollte. Durchgehend dunkles Navy bis Fast-Schwarz, eine hochwertige Display-Serif (Utopia Std Display) für alle Headlines, Montserrat ausschließlich für Funktionales, ein einziger roter Akzent für Interaktion. Die Bildsprache ist kinematografisch: Flaschen auf Stein, dunkle Kellerszenen, alles in derselben kühlen Lichtstimmung. Die Landkarte mit den Gütern ist eine eigene Illustration mit Aufklapp-Logik. Auffällig: Der Shop heißt nicht „Shop“, sondern „Wine Shop“, „Wine Club“, „Wine Tour“, „Wine Concierge“ – Kommerz wird zu Zugehörigkeit umformuliert.",
 "palette":[("#002450","Navy (Marke)"),("#0b1420","Fast-Schwarz (Sektion)"),("#c0392b","Rot (Akzent, Interaktion)"),("#ffffff","Weiß (Typo auf dunkel)"),("#d9d9d9","Sekundärtext")],
 "fonts":"Utopia Std Display (Serif) + Montserrat (UI/Body)",
 "type":[("H2","Utopia Std Display 31/34 px · w400 · weiß","Our Wines"),("H3","Utopia Std Display 40/42 px · w400 · weiß","Estate-Titel"),("Body","Montserrat 16/24 px · w400 · weiß","Fließtext auf dunklem Grund"),("Nav","Montserrat 12 px · w600 · UPPERCASE","WINES / ESTATES / HERITAGE"),("Link","Utopia Italic + Linie","Discover More ———")],
 "layout":"Container 1512 px, Vollbild-Sektionen, Seitenlänge 5.714 px. Sehr großzügiger vertikaler Rhythmus, halbseitige Bild/Text-Splits, keine Kachelraster.",
 "imagery":"Video-Hero, dunkle Produktfotografie (Flaschen auf Stein, auf Samt), illustrierte Italienkarte mit Gut-Markern. Konsequent kühle, dunkle Lichtstimmung über die gesamte Seite.",
 "commerce":"„Wine Club“ als Navy-Pill (r18 px) fix oben rechts, Wine Shop / Wine Tour / Wine Concierge als eigene Navigationspunkte, Wishlist-Icon, weiße Pill-Buttons „Discover more“ auf dunklem Grund.",
 "motion":"Sanfte Fades beim Scrollen, Akkordeon für die Güter, sonst sehr zurückhaltend.",
 "take":["Dunkle Grundfläche als Markenraum – nicht nur für einzelne Sektionen","Display-Serif für Headlines, Grotesk ausschließlich für UI","Kursive Serif-Links mit Strich statt Buttons („Discover More ———“)","Kommerz sprachlich als Zugehörigkeit: Club, Tour, Concierge statt Shop","Eigene Kartenillustration für Lagen/Güter"],
 "avoid":["Sehr JS-lastiger Aufbau: Inhalte erscheinen mit spürbarer Verzögerung","Chat-Widget und Club-Pill gleichzeitig über dem Content"],
 "shots":[("mazzei-1.jpg","„Our Wines“ – Serif-Headline auf Navy, sehr großzügiger Raum"),("mazzei-2.jpg","Dunkle Produktfotografie: Flaschen auf Stein, gleiche Lichtstimmung"),("mazzei-3.jpg","Illustrierte Karte der Güter mit Datenblatt und Akkordeon")],
},
{
 "slug":"pfeifer","name":"Weingut Pfeifer","url":"https://www.pfeifer-weingut.at/onlineshop.html",
 "cat":"Shop","catKey":"shop","score":2,"platform":"Individueller Shop, sehr lange Seite",
 "claim":"Funktionierender Shop, Optik aus dem Rabatt-Repertoire.",
 "verdict":"Sandfarbene Fläche, Abril Display als Headline-Serif und eine schmale Grotesk – die Zutaten sind nicht schlecht. Der Auftritt kippt aber durch die Menge an Verkaufssignalen: Aktions-Rosetten, „Neuer Jahrgang!“-Fahnen, Gratisversand-Störer, Rabattbanner, dazu eine 10.500 px lange Seite. Die Flaschen sind freigestellt vor Sandfläche montiert, wodurch der Grid wie ein Katalog wirkt. Als Mechanik-Referenz brauchbar, als Gestaltungsreferenz nicht.",
 "palette":[("#e4dec5","Sand"),("#333333","Text"),("#4a4949","Sekundärtext"),("#ffffff","Weiß"),("#e5e5e5","Fläche")],
 "fonts":"Abril Display (Serif) + Texta (Grotesk)",
 "type":[("H1","Abril Display 40/40 px · w700 · #333","Unser Onlineshop"),("H2","Abril Display 35/46 px · w700","Sektionstitel"),("H3","Abril Display 18/23 px · w800","Produktname"),("Body","Texta 20 px · w400","Fließtext"),("Nav","Texta 18 px · w700 · ls 2 px · UPPERCASE","WEINGUT / ONLINESHOP")],
 "layout":"Container 1400 px, Radius 10 px, Seitenlänge 10.510 px. Topbar mit Öffnungszeiten, Telefonnummer, Login und „Zimmer buchen“. Produktraster 4-spaltig.",
 "imagery":"14 Bilder, überwiegend 3:4. Freigestellte Flaschen, Blattornamente als Wasserzeichen im Hintergrund.",
 "commerce":"Preis, Mengen-Stepper und Warenkorb-Icon direkt in der Kachel. Aktionsrosetten („12er Sommer-Paket“, „-5 % Rabatt ab EUR 150“), Gratisversand-Störer, Jahrgangsfahnen.",
 "motion":"Kaum Bewegung.",
 "take":["Mengen-Stepper direkt in der Produktkachel (funktioniert gut für 6er/12er-Gebinde)","Öffnungszeiten und Telefon in der Topbar – für Ab-Hof-Verkauf sinnvoll"],
 "avoid":["Aktions-Rosetten und Störer über den Flaschen","Grellgrüner Cookie-Button, der alles andere übertönt","Blattornamente als Hintergrund-Wasserzeichen","Seiten über 10.000 px Länge ohne Zwischennavigation"],
 "shots":[("pfeifer-1.jpg","Einstieg mit Sandfläche, Blattornamenten und Cookie-Dialog"),("pfeifer-2.jpg","Produktraster mit freigestellten Flaschen, Aktionsrosetten und Steppern")],
},
{
 "slug":"artner","name":"Weingut Artner","url":"https://weingut-artner.at/",
 "cat":"Shop / klein","catKey":"shop","score":2,"platform":"WordPress + WooCommerce",
 "claim":"Mutige Farbe, umgekehrte Schriftlogik, wenig Substanz.",
 "verdict":"Auffällig ist die durchgehend hellblaue Grundfläche und die umgekehrte Schriftpaarung: eine sehr fette Grotesk (Cabin w900) für Headlines und eine Serif (Crimson Text) für den Fließtext – normalerweise andersherum. Das kann funktionieren, wirkt hier aber unfertig, weil kaum Inhalt vorhanden ist (Seitenlänge nur 2.433 px, ein einziges Foto) und große Flächen leer bleiben. Der Shop hängt als runder Badge oben rechts und ist inhaltlich abgekoppelt.",
 "palette":[("#d0dfea","Hellblau (Grundfläche)"),("#ffffff","Weiß"),("#f7f4f2","Warmes Weiß"),("#2c2c2c","Text"),("#8a8785","Sekundärtext")],
 "fonts":"Cabin (Grotesk, w900) + Crimson Text (Serif, Body)",
 "type":[("H1","Cabin 56/56 px · w900 · schwarz","Neue Wege mit Alexander Artner"),("H2","Cabin 35/35 px · w900","Sektionstitel"),("Body","Crimson Text 28/48 px · w400 · #2c2c2c","Sehr großer Serif-Fließtext")],
 "layout":"Container 1200 px, Seitenlänge nur 2.433 px, Sektions-Padding 65 px. Viel ungenutzte Fläche zwischen den Blöcken.",
 "imagery":"Ein einziges großes Schwarzweiß-Familienporträt vor Holzfässern.",
 "commerce":"Runder „ZUM SHOP“-Badge (r 42 px) fix oben rechts, Warenkorb-Icon im Header.",
 "motion":"Keine nennenswerte.",
 "take":["Schwarzweiß-Porträt der Familie als einziges Bild – hohe Wirkung durch Reduktion","Farbige Grundfläche statt Weiß"],
 "avoid":["Serif für den Fließtext bei 28 px – schlecht lesbar auf Länge","Große leere Flächen ohne gestalterische Absicht","Shop als abgekoppelter Badge statt integrierter Bereich"],
 "shots":[("artner-1.jpg","Hellblaue Grundfläche, fette Grotesk-Headline, runder Shop-Badge"),("artner-2.jpg","Schwarzweiß-Familienporträt vor Holzfässern")],
},
{
 "slug":"aumann","name":"Leo Aumann","url":"https://www.aumann.at/de/weinshop/online-weinshop.html",
 "cat":"Shop","catKey":"shop","score":3,"platform":"Individueller Shop",
 "claim":"Sauberer Shop mit gutem Typo-Ansatz, kaputt gemacht durch Rabattlogik.",
 "verdict":"Prata als Display-Serif über Vollbild-Landschaft plus Open Sans Light für den Fließtext ist eine tragfähige Kombination, und die Kachel mit dünner Umrandung ist ruhiger als die meisten Mitbewerber. Die Preisdarstellung mit durchgestrichenem Vorher-Preis, die schwarze „5+1 gratis“-Rosette und das Aktions-Popup ziehen den Auftritt aber sofort in Richtung Diskont. Burgunderrot taucht als Akzent auf, wird aber kaum genutzt.",
 "palette":[("#2b2b2a","Anthrazit (Basis)"),("#d8dcdb","Kühles Grau"),("#651d32","Burgunder (Akzent)"),("#d0d3d4","Linien"),("#ffffff","Weiß")],
 "fonts":"Prata (Display-Serif) + Open Sans (Light/Regular/Semibold)",
 "type":[("H1","Prata 62/74 px · w400 · weiß auf Bild","genuss mit charakter"),("H2","Prata 40/48 px · w400","Alle Produkte"),("Body","Open Sans Light 18/29 px · w300","Fließtext"),("Nav","Open Sans Semibold 15 px · UPPERCASE","WEINGUT / HEURIGER / ONLINE SHOP")],
 "layout":"Vollbild-Hero mit Fassadenmotiv, darunter Filterzeile und Produktraster mit dünn umrandeten Kacheln. Seitenlänge 11.203 px.",
 "imagery":"12 Bilder, überwiegend 3:4. Architektur- und Weingartenmotive, freigestellte Flaschen im Raster.",
 "commerce":"Mengen-Stepper und dunkler Warenkorb-Button je Kachel, Literangabe, durchgestrichener Vorher-Preis, „5+1 gratis“-Rosette, Aktions-Popup, Kalender-Icon für den Heurigen, DE/EN.",
 "motion":"Zurückhaltend.",
 "take":["Prata über Vollbild-Fassadenmotiv – wirkt in der Kombination hochwertig","Dünn umrandete Produktkachel statt Schatten und Karte","Kalender-Icon im Header für Heurigen-/Öffnungstermine","Zweisprachigkeit sauber im Header"],
 "avoid":["Durchgestrichene Preise und „gratis“-Rosetten im Premiumsegment","Aktions-Popup, das sich über das Produktraster legt","Vierstufiger Cookie-Dialog mit grünem Zustimmen-Button"],
 "shots":[("aumann-1.jpg","Vollbild-Hero mit Prata-Claim, darunter Filterzeile"),("aumann-2.jpg","Produktraster mit Steppern, Streichpreisen und Aktions-Popup")],
},
{
 "slug":"krispel","name":"Genussgut Krispel","url":"https://www.krispel.at/",
 "cat":"Marke / Genussgut","catKey":"marke","score":5,"platform":"WordPress + WooCommerce, individuell gestaltet",
 "claim":"Der gestalterisch stärkste österreichische Auftritt der Liste.",
 "verdict":"Hier hat jemand eine Marke gebaut, keine Website. Aprikose auf Creme mit Petrol als Gegenpol, eine kursive Serif (Mackay) für die emotionalen Zeilen, DIN Pro in 79 px für die lauten, und alles konsequent kleingeschrieben. Der Schriftzug „krispel“ läuft als riesiges Wasserzeichen durch den Hintergrund. Die Navigation ist nach Geschäftsbereichen sortiert – Genussgut, Wein, Restaurant, Erlebnisse – der Shop ist rechts angesetzt, nicht im Zentrum. Genau diese Struktur passt zu einem Weingut mit Verkostung und Gastronomie. Einzige Einschränkung: Die Tonalität ist warm-verspielt, nicht luxuriös – für „premium“ müsste die Farbwelt kühler und dunkler werden.",
 "palette":[("#fff3e8","Creme (Grundfläche)"),("#f9bc88","Aprikose (Marke)"),("#fee0c9","Aprikose hell"),("#204c52","Petrol (Typo)"),("#d04c20","Orangerot (Akzent)")],
 "fonts":"Mackay (Serif, kursiv für Kicker) + DIN Pro (Headlines und Body)",
 "type":[("H2","DIN Pro 79/84 px · w400 · UPPERCASE · #204c52","Große Sektionstitel"),("Kicker","Mackay kursiv · #204c52","unser wein"),("H3","DIN Pro 25/38 px · w500 · UPPERCASE","Zwischenzeile"),("Body","DIN Pro 16/24 px · w400 · #204c52","Fließtext"),("Nav","DIN Pro 16 px · UPPERCASE · #f9bc88","GENUSSGUT / WEIN / RESTAURANT")],
 "layout":"Volle Breite ohne harten Container, Seitenlänge 11.340 px. Vier Einstiegskacheln direkt unter dem Header (wein / restaurant / shop / erlebnisse), danach großflächige Farbfelder.",
 "imagery":"14 Bilder, überwiegend 3:4 Hochformat, 2 Videos. Menschen bei Tisch, Hände, Detailaufnahmen – durchgehend warme Farbstimmung, sehr konsistent.",
 "commerce":"Shop ist gleichrangig, aber nicht dominant. Warenkorb und Konto als Icons rechts, Buttons als Outline mit 1,5 px Linie, keine Flächen.",
 "motion":"Sanfte Parallax-Effekte, Hover-Zoom auf den Einstiegskacheln.",
 "take":["Navigation nach Geschäftsbereichen statt nach Produktkategorien","Kursive Serif als Kicker über einer großen Grotesk-Zeile","Konsequente Kleinschreibung als Markenhaltung","Riesiger Wortmarken-Schriftzug als Hintergrundebene","Outline-Buttons mit 1,5 px Linie statt gefüllter Flächen"],
 "avoid":["Zwei zusätzliche Farben (Orangerot neben Aprikose) verwässern die Palette leicht","Cookie-Banner nimmt ein Drittel des Bildschirms ein"],
 "shots":[("krispel-1.jpg","Vier Einstiegskacheln (wein / restaurant / shop / erlebnisse) über Wortmarken-Wasserzeichen"),("krispel-2.jpg","Kursiver Serif-Kicker über großer Grotesk-Zeile, konsequent kleingeschrieben")],
},
{
 "slug":"scharl","name":"Weinhof Scharl","url":"https://weinhof-scharl.at/",
 "cat":"Marke / Editorial","catKey":"marke","score":4,"platform":"WordPress + Elementor + WooCommerce",
 "claim":"Reines Schwarzweiß, Magazinlogik – überraschend stark.",
 "verdict":"Kein einziger Farbton außer Schwarz und Weiß. DM Serif Display trägt die gesamte Erzählung, PT Sans hält den Rest neutral. Der Aufbau folgt einem Magazin: schmale zentrierte Textspalte, große Serif-Zitate über die volle Breite, versetztes Bildraster mit Hochformaten. Die gezeichnete Schiebermütze als Bildmarke gibt der Marke ein Gesicht, ohne folkloristisch zu werden. Der senkrechte „Öffnungszeiten“-Reiter in Flaschenform am rechten Rand ist eine eigenständige, charmante Lösung.",
 "palette":[("#000101","Schwarz"),("#ffffff","Weiß"),("#fafafa","Grauweiß"),("#5f5f5f","Sekundärtext")],
 "fonts":"DM Serif Display (Headlines) + PT Sans (Body/Nav)",
 "type":[("H1","DM Serif Display 58/81 px · w400 · schwarz","Charakter erkennt man schon von Weitem."),("H2","DM Serif Display 42/55 px · w400","Zitatzeile über volle Breite"),("H3","DM Serif Display 32/42 px · w400","Zwischentitel"),("Body","PT Sans 14/29 px · w400","Fließtext, sehr großzügige Zeilenhöhe"),("Nav","PT Sans 14 px · w500 · UPPERCASE","CHARAKTERWEINE / KULINARIK")],
 "layout":"Container 1200 px, Seitenlänge 6.306 px. Zentrierte schmale Textspalte im Hero, danach versetztes Bildraster, dazwischen ganzseitige Serif-Zitate.",
 "imagery":"11 Bilder, 16:9 und 3:4 gemischt. Reportagefotografie: Person vor Wand, Hände mit Trauben, Architektur in der Landschaft. Sehr einheitliche, helle Bildstimmung.",
 "commerce":"Schwarzer „ONLINESHOP“-Button im Header, Warenkorb- und Konto-Icon daneben. Senkrechter Öffnungszeiten-Reiter in Flaschenform am rechten Bildrand.",
 "motion":"Sparsam, Einblendungen beim Scrollen.",
 "take":["Konsequentes Schwarzweiß – funktioniert, wenn die Fotografie stark ist","Ganzseitige Serif-Zitate als Rhythmuswechsel zwischen Bildstrecken","Gezeichnete Bildmarke statt Wappen oder Trauben","Versetztes Bildraster statt gleichförmiger Kacheln","Zeilenhöhe 29 px bei 14 px Schrift – sehr ruhiger Lesefluss"],
 "avoid":["14 px Fließtext ist an der unteren Grenze","Consent-Layer, der ein Drittel der Seite einnimmt"],
 "shots":[("scharl-1.jpg","Zentrierte Serif-Headline, schmale Textspalte, Flaschen-Reiter rechts"),("scharl-2.jpg","Editoriales Bild-Text-Layout mit versetztem Raster")],
},
{
 "slug":"dam","name":"Weingut & Vinothek Dam","url":"https://www.weingut-dam.at/",
 "cat":"Shop","catKey":"shop","score":2,"platform":"Wix",
 "claim":"Freundlich, jung, aber sichtbar Baukasten.",
 "verdict":"Terrakotta und warmes Weiß, Playfair Display für die Headlines, ein runder Stempel mit „#DAMTASTISCH – EINS BIS ENDLOS“ als Bildmarke. Die Tonalität ist bewusst locker („Schön, dass du da bist!“, „SERVUS“). Technisch ist es eine Wix-Seite, was man an den generischen Schriftreferenzen und der Struktur erkennt. Das Newsletter-Modal mit -5 % erscheint sofort. Für ein Premium-Weingut ist der Ton zu leger und der Aufbau zu wenig eigenständig.",
 "palette":[("#b76354","Terrakotta"),("#cdc5bf","Warmes Grau"),("#fdfbf8","Warmweiß"),("#727557","Olive"),("#ffffff","Weiß")],
 "fonts":"Playfair Display (Headlines) + Wix-Systemschriften (Body)",
 "type":[("H1","Playfair Display 49 px · w400 · weiß auf Bild","Schön, dass du da bist!"),("H2","Playfair Display 49 px · w400","FLASCHENPOST"),("Body","16/36 px · w400","Fließtext mit sehr großer Zeilenhöhe")],
 "layout":"Seitenlänge 4.562 px. Zentrierter Vollbild-Hero, darunter Produktraster 4-spaltig mit „biologisch“-Tags.",
 "imagery":"Wenige eigene Bilder, dafür Flaschen-Gruppenaufnahme im Newsletter-Modal. Etiketten mit römischen Ziffern (I, III, IV, V, X) als eigenständiges Gestaltungselement.",
 "commerce":"Produktkacheln mit Name, Preis und Versanddetails, „biologisch“-Tag oben links, handgeschriebener Störer „JETZT ONLINE BESTELLEN!“, Newsletter-Modal mit -5 %.",
 "motion":"Wix-Standardanimationen.",
 "take":["Römische Ziffern auf den Etiketten als Serien-System – überträgt sich gut auf die Website","Runder Stempel als sekundäre Bildmarke"],
 "avoid":["Newsletter-Modal mit Rabatt direkt beim Einstieg","Handgeschriebene Störer im Header","Duz-Ansprache und Ausrufezeichen im Premiumkontext","Sichtbare Baukasten-Struktur"],
 "shots":[("dam-1.jpg","Terrakotta-Header mit rundem Stempel und handgeschriebenem Störer"),("dam-2.jpg","Produktraster mit Newsletter-Modal „FLASCHENPOST“ (-5 %)")],
},
{
 "slug":"eder","name":"Weingut Eder","url":"https://www.weingut-eder.at/",
 "cat":"Shop / Marke","catKey":"shop","score":3,"platform":"WordPress + WooCommerce",
 "claim":"Gold und fette Serif – handwerklich, nicht luxuriös.",
 "verdict":"Ein Gold-Ton trägt die gesamte Seite: Logo, Buttons, Zierlinien, Etiketten. Breve Display ist eine fette, charaktervolle Serif, die den Headlines Wucht gibt, Lato hält den Rest neutral. Der Split-Hero (Bild links, Claim rechts) ist gut gelöst. Die Produktkacheln sind mit abgerundeten Rahmen, Falstaff-Punkterosetten, Gold-Medaillen und gezeichneten Schnörkel-Trennern allerdings deutlich überdekoriert – jedes Element will Aufmerksamkeit.",
 "palette":[("#c8a763","Gold (Marke)"),("#000000","Schwarz"),("#eae7e3","Warmgrau"),("#ffffff","Weiß")],
 "fonts":"Breve Display (fette Serif) + Lato (Body)",
 "type":[("H1","Breve Display 60/72 px · w400 · schwarz","einzigartiger wein vom wagram."),("H3","Breve Display 45/54 px · w400","riedenweine 2025 out now."),("H2","Lato 20/24 px · UPPERCASE","UNSERE WEINE"),("Body","Lato 16/28 px · w400","Fließtext"),("Kicker","Lato 17/28 px · w500 · UPPERCASE · #c8a763","Goldene Auszeichnungszeile")],
 "layout":"Seitenlänge 3.564 px, Sektions-Padding 64 px. Split-Hero: Bild links bündig, Claim und Button rechts. Produktraster 4-spaltig.",
 "imagery":"11 Bilder, fast alle 1:1. Flaschen im Traggestell, freigestellte Einzelflaschen. Etiketten mit Illustrationen (Streichhölzer, Labyrinth, Nüsse) als Serie.",
 "commerce":"Pill-Buttons mit 800 px Radius in Gold, Produktkachel mit Rahmen (r 6 px), Falstaff-Punkterosette, „GOLD 2026“-Medaille, gezeichneter Schnörkel-Trenner, „IN DEN WARENKORB“.",
 "motion":"Einblendungen beim Scrollen.",
 "take":["Split-Hero: Bild randlos links, Claim und CTA rechts im Weißraum","Illustrierte Etikettenserie als verbindendes Gestaltungselement","Genau ein Metallton statt Gold plus Bordeaux plus Ornament"],
 "avoid":["Punkterosetten und Medaillen direkt auf der Produktkachel","Gezeichnete Schnörkel-Trenner unter jedem Produktnamen","Vollrunde Pill-Buttons (r 800 px) wirken im Premiumsegment weich"],
 "shots":[("eder-1.jpg","Split-Hero: Flaschen links randlos, Claim und Gold-Button rechts"),("eder-2.jpg","Produktraster mit Rahmen, Punkterosetten und Schnörkel-Trennern")],
},
{
 "slug":"colterenzio","name":"Colterenzio — Führung & Verkostung","url":"https://www.colterenzio.it/fuehrung-verkostung/",
 "cat":"Erlebnis / Buchung","catKey":"erlebnis","score":4,"platform":"Individuell, dreisprachig",
 "claim":"Die beste Buchungsmechanik der Liste – emotional aber unterkühlt.",
 "verdict":"Für die Frage „wie verkaufe ich Führungen und Verkostungen“ ist das die brauchbarste Referenz. Jede Erlebnisvariante ist eine eigene Karte mit demselben Aufbau: Bild, Titel, Beschreibung, Dauer mit Uhr-Icon, Preis pro Person, dunkler Button. Dadurch sind vier Angebote in Sekunden vergleichbar. Die Sprachhinweise („ONLY IN GERMAN AND ITALIAN“) stehen direkt in der Beschreibung – für ein Weingut mit internationalen Gästen wichtig. Gestalterisch ist es allerdings sehr nüchtern: weiß, Helvetica, kaum Emotion. Die feste Seitenleiste mit Logo, Menü und Sprachumschalter ist eine gute Lösung für mehrsprachige Auftritte.",
 "palette":[("#ffffff","Weiß"),("#f5f5f5","Kartenfläche"),("#35373d","Button dunkel"),("#1e1e1c","Text"),("#8d8d8d","Metadaten"),("#162931","Fließtext")],
 "fonts":"Helvetica Neue LT (Headlines) + Poppins Light (Body)",
 "type":[("H2","Helvetica Neue LT 30/36 px · w400 · ls 6 px · UPPERCASE","GUIDED TOURS & TASTINGS"),("H3","Helvetica Neue LT 31/37 px · w400","Kartentitel"),("Body","Poppins 16/24 px · w300 · #162931","Beschreibung")],
 "layout":"Feste linke Seitenleiste (Logo, Menü, Sprache), Content rechts. Seitenlänge nur 2.273 px – bewusst kurz. Kartenraster 3-spaltig, Radius 6 px.",
 "imagery":"Reportagefotos der Führungen selbst: Menschen im Keller, im Weingarten, Kräuterkorb. Kein Stockmaterial.",
 "commerce":"Erlebniskarte mit fixem Aufbau: Bild 16:9 → Titel → Beschreibung → Uhr-Icon + Dauer → Preis „€ 50,00 / Person“ → dunkler Button „Find out“. Sprachhinweis direkt in der Beschreibung.",
 "motion":"Keine.",
 "take":["Erlebniskarte mit immer gleichem Aufbau: Bild, Titel, Dauer, Preis pro Person, ein Button","Dauer mit Uhr-Icon als eigenes Datenfeld","Sprachhinweis direkt am Angebot","Feste Seitenleiste mit Sprachumschalter für mehrsprachige Auftritte","Bewusst kurze Seite (2.273 px) – Buchen statt Scrollen"],
 "avoid":["Helvetica mit 6 px Laufweite wirkt technisch, nicht gastlich","Weiße Grundfläche ohne jede Markenfarbe","Bilder laden verzögert nach – Platzhalter-Icons sind sichtbar"],
 "shots":[("colterenzio-1.jpg","Seitenleiste links, gesperrte Versalzeile, Reportagebild der Führung"),("colterenzio-2.jpg","Erlebniskarten mit Dauer, Preis pro Person und einheitlichem Button")],
},
{
 "slug":"michael","name":"Weingut Michael — Verkostung","url":"https://www.weingut-michael.at/verkostung",
 "cat":"Erlebnis / Buchung","catKey":"erlebnis","score":3,"platform":"Wix",
 "claim":"Emotional richtig aufgebaut, technisch Baukasten.",
 "verdict":"Die Verkostungsseite macht inhaltlich vieles richtig: goldener Kicker („WEINVERKOSTUNG MIT GENUSSTELLER“), große Headline mit Ortsbezug („Ein genussvoller Nachmittag am Rosenberg“), ein Satz, der konkret sagt was enthalten ist – acht Weine, ein Genussteller, Einblicke in die Vinifizierung – und genau ein Button „TERMIN BUCHEN“. Das Abendlicht-Panorama über die volle Breite trägt die Stimmung. Schwächer ist die Umsetzung: Wix-Baukasten, generische Schriftreferenzen, Gold als einziger Marken-Anker.",
 "palette":[("#bfa760","Gold (Marke)"),("#fcf8ed","Creme"),("#7d9174","Salbeigrün"),("#303030","Text"),("#ffffff","Weiß")],
 "fonts":"Wix-Serif (Headlines) + Avenir LT Light (Body)",
 "type":[("H1","Serif 60/66 px · w400 · #bfa760","Ein genussvoller Nachmittag am Rosenberg"),("H3","Serif 45/54 px · w400 · Gold","Zwischentitel"),("Body","Avenir LT Light 18/29 px · #303030","Beschreibungstext"),("Kicker","Gesperrte Versalien · Gold","WEINVERKOSTUNG MIT GENUSSTELLER")],
 "layout":"Seitenlänge 5.133 px. Vollbild-Hero mit Abendlicht-Panorama, Textblock linksbündig auf ca. 40 % Breite, ein Button.",
 "imagery":"Abendliches Weingartenpanorama als Hero. Wenige weitere Bilder.",
 "commerce":"Goldener Button „TERMIN BUCHEN“ (r 5 px), Shop-Button separat im Header, Warenkorb und Login rechts.",
 "motion":"Wix-Standard.",
 "take":["Kicker + Headline mit Ortsbezug + ein konkreter Inhaltssatz + genau ein Button","Leistungsumfang wörtlich benennen: acht Weine, ein Genussteller, Einblicke in die Vinifizierung","Linksbündiger Textblock auf 40 % Breite über Vollbild-Panorama","Verkostung als eigener Hauptnavigationspunkt, nicht unter „Kontakt“"],
 "avoid":["Gold als einziger Markenanker ohne zweite Farbe","Sichtbare Baukasten-Struktur","Login-Avatar überlappt den Menüpunkt „KONTAKT“"],
 "shots":[("michael-1.jpg","Verkostungs-Hero: goldener Kicker, Headline mit Ortsbezug, ein Buchungs-Button")],
},
]
